---
- hosts: all
  become: yes
  vars:
    repo_packages:
      - "epel-release"
      - "http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm"
      - "http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm" # for git 2.x
    packages:
      - "libselinux-python"
      - "python-meld3"
      - "rubygems"
      - "git"
      - "gcc"
      - "patch"
      - "openssl-devel"
      - "mysql-community-devel"
      - "libcurl"
      - "libcurl-devel"
      - "bison"
      - "bison-devel"
      - "libjpeg-turbo"
      - "libjpeg-turbo-devel"
      - "libpng"
      - "libpng-devel"
      - "libmcrypt"
      - "libmcrypt-devel"
      - "readline"
      - "readline-devel"
      - "libtidy"
      - "libtidy-devel"
      - "autoconf"
      - "automake"
      - "libxml2-devel"
      - "libxslt-devel"
      # for installing PHP
      - "bzip2-devel"
      - "libicu-devel"
      - "gcc-c++"

  tasks:
    - name: install repo packages
      yum:
        name: "{{ repo_packages }}"
        state: "installed"

    - name: install packages
      yum:
        name: "{{ packages }}"
        state: "installed"

    - name: disable SELinux
      selinux: state=disabled
