---
- hosts: all
  become: yes
  tasks:
    - name: install packages
      yum:
        name: "python-setuptools"

    - name: install supervisord
      ignore_errors: yes
      easy_install:
        name: supervisor
      register: supervisor_result

    - name: fallback in case of failure (see https://github.com/ansible/ansible/issues/23534)
      command: easy_install supervisor
      when: supervisor_result.failed == true

    - name: copy supervisord init
      shell: |
        cp /tmp/isucon4/qualifier/ami/files/supervisord.init /etc/init.d/supervisord
        chmod a+x /etc/init.d/supervisord

    - name: enable supervisord service
      service:
        name: "supervisord"
        enabled: true

    - name: copy supervisord configuration
      shell: cp /tmp/isucon4/qualifier/ami/files/supervisord.conf /etc/supervisord.conf
      notify:
        - restart supervisord

  handlers:
    - name: restart supervisord
      service:
        name: "supervisord"
        state: "restarted"
