---
- hosts: all
  become_user: isucon
  become: yes
  vars:
    git_repo: "https://github.com/tagomoris/xbuild.git"
    versions:
      ruby: "2.3.3"
      node: "v0.10.31"
      python: "2.7.8"
      perl: "5.20.0"
      php: "5.6.0"

  tasks:
    - name: clone xbuild repo
      git:
        repo: "{{ git_repo }}"
        dest: "/home/isucon/.xbuild/"

    # ruby
    - name: install ruby
      command: /home/isucon/.xbuild/ruby-install {{ versions.ruby }} /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby

    - name: gem install
      command: /home/isucon/env.sh gem install --no-rdoc --no-ri foreman
      args:
        creates: /home/isucon/.local/ruby/bin/foreman

    - name: bundle install
      command: /home/isucon/env.sh bundle install
      args:
        chdir: /home/isucon/webapp/ruby

    # node
    - name: install node
      command: /home/isucon/.xbuild/node-install {{ versions.node }} /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node

    - name: npm install
      command: /home/isucon/env.sh npm install
      args:
        chdir: /home/isucon/webapp/node

    # python
    - name: install python
      command: /home/isucon/.xbuild/python-install {{ versions.python }} /home/isucon/.local/python
      args:
        creates: /home/isucon/.local/python/bin/python

    - name: pip install
      command: /home/isucon/env.sh pip install gunicorn Flask MySQL-python
      args:
        creates: /home/isucon/.local/python/bin/gunicorn

    # perl
    - name: install perl
      shell: /home/isucon/.xbuild/perl-install {{ versions.perl }} /home/isucon/.local/perl; test -x /home/isucon/.local/perl/bin/perl
      args:
        creates: /home/isucon/.local/perl/bin/perl

    - name: carton install
      command: /home/isucon/env.sh carton install
      args:
        chdir: /home/isucon/webapp/perl

    # php
    - name: install php
      command: /home/isucon/.xbuild/php-install {{ versions.php }} /home/isucon/.local/php
      args:
        creates: /home/isucon/.local/php/bin/php

    - name: copy the php.ini file
      shell: |
        cp /tmp/isucon4/qualifier/ami/files/php.ini /home/isucon/.local/php/etc/php.ini
        chown isucon:isucon /home/isucon/.local/php/etc/php.ini
