---
- hosts: all
  become: yes
  tasks:
    - name: install packages
      yum:
        name: "{{ packages }}"
        state: "installed"
      vars:
        packages:
          - "git"
          - "mercurial"
          - "bzr"

    - name: download go
      command: "curl -L -O  http://golang.org/dl/go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go

    - name: install go
      command: "tar -C /usr/local -xzf go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go

    - name: copy the golang.sh file
      shell: cp /tmp/isucon4/qualifier/ami/files/golang.sh /etc/profile.d/golang.sh

    - name: gem install
      command: "/usr/bin/gem install --no-rdoc --no-ri gondler -v 0.2.0"
      args:
        creates: /usr/local/bin/gondler

    - name: run build.sh
      command: /home/isucon/env.sh ./build.sh
      args:
        chdir: /home/isucon/webapp/go

    - name: change the ownership of /home/isucon/gocode/
      file:
        path: "/home/isucon/gocode"
        state: "directory"
        owner: "isucon"
        group: "isucon"
        recurse: yes
