---

- hosts: all
  become: yes
  vars:
    go_version: "1.11"
    gondler_version: "0.2.0"
    isucon:
      username: "isucon"
      group: "isucon"

  tasks:
    - name: install packages
      yum:
        name: "{{ packages }}"
        state: "installed"
      vars:
        packages:
          - "git"
          - "mercurial"
          - "bzr"

    - name: install go
      unarchive:
        src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/usr/local/"
        remote_src: yes
        creates: "/usr/local/go/"

    - name: copy the golang.sh file
      shell: cp /tmp/isucon4/qualifier/ami/files/golang.sh /etc/profile.d/golang.sh

    - name: gem install
      command: "/usr/bin/gem install --no-rdoc --no-ri gondler -v {{ gondler_version }}"
      args:
        creates: /usr/local/bin/gondler

    - name: run build.sh
      command: /home/isucon/env.sh ./build.sh
      args:
        chdir: /home/isucon/webapp/go

    - name: change the ownership of /home/isucon/gocode/
      file:
        path: "/home/isucon/gocode"
        state: "directory"
        owner: "{{ isucon.username }}"
        group: "{{ isucon.group }}"
        recurse: yes
