---

- hosts: all
  become: yes
  vars:
    isucon:
      username: "isucon"
      group: "isucon"

  tasks:
    - name: remove the existing build file
      file:
        path: "/tmp/benchmarker/"
        state: "absent"

    - name: copy the benchmarker files
      shell: rsync -aL --delete /tmp/isucon4/qualifier/benchmarker /tmp/

    - name: change the ownership of /tmp/benchmarker/
      file:
        path: "/tmp/benchmarker/"
        state: "directory"
        owner: "{{ isucon.username }}"
        group: "{{ isucon.group }}"
        recurse: yes

    - name: edit the Makefile
      lineinfile:
        dest: "/tmp/benchmarker/Makefile"
        state: "present"
        regexp: "{{ item.regexp }}"
        line: "{{ item.replace }}"
      with_items:
        - { regexp: '^GIT_COMMIT=.*', replace: 'GIT_COMMIT=""' }
        - { regexp: '-X main\.GIT_COMMIT \\"\$\{GIT_COMMIT\}\\" \\', replace: '        -X main.GIT_COMMIT=${GIT_COMMIT} \' }
        - { regexp: '-X github\.com/isucon/isucon4/qualifier/benchmarker/user\.DummyUsersTSVMD5 \\"\$\{DUTMH\}\\" \\', replace: '        -X github.com/isucon/isucon4/qualifier/benchmarker/user.DummyUsersTSVMD5=${DUTMH} \'}
        - { regexp: '-X github\.com/isucon/isucon4/qualifier/benchmarker/user\.DummyUsersUsedTSVMD5 \\"\$\{DUUTMH\}\\" \\', replace: '        -X github.com/isucon/isucon4/qualifier/benchmarker/user.DummyUsersUsedTSVMD5=${DUUTMH} \' }
        - { regexp: '-X github\.com/isucon/isucon4/qualifier/benchmarker/user\.DebugMode \\"\$\{debugmode\}\\" \\', replace: '        -X github.com/isucon/isucon4/qualifier/benchmarker/user.DebugMode=${debugmode} \' }
        - { regexp: '-X main\.DebugMode \\"\$\{debugmode\}\\" \\', replace: '        -X main.DebugMode=${debugmode} \' }
        - { regexp: '-X main\.SkipMetadataMode \\"\$\{skipmetadata\}\\"', replace: '        -X main.SkipMetadataMode=${skipmetadata}' }

    - name: remove the machine type check in main.go
      lineinfile:
        dest: "/tmp/benchmarker/main.go"
        state: "present"
        regexp: 'checkInstanceMetadata\(\)'
        line: ''

    - name: build benchmarker
      command: /home/isucon/env.sh make release
      become_user: "{{ isucon.username }}"
      ignore_errors: yes
      args:
        chdir: /tmp/benchmarker

    - name: mv the build file to /home/isucon/
      command: mv /tmp/benchmarker/benchmarker /home/isucon/
      become_user: "{{ isucon.username }}"
