---

- hosts: all
  become: yes
  vars:
    isucon:
      username: "isucon"
      group: "isucon"

  tasks:
    - name: remove the existing build file
      file:
        path: "/tmp/benchmarker/"
        state: "absent"

    - name: copy the benchmarker files
      shell: rsync -aL --delete /tmp/isucon4/qualifier/benchmarker /tmp/

    - name: change the ownership of /tmp/benchmarker/
      file:
        path: "/tmp/benchmarker/"
        state: "directory"
        owner: "{{ isucon.username }}"
        group: "{{ isucon.group }}"
        recurse: yes

    - name: build benchmarker
      command: /home/isucon/env.sh make release
      become_user: "{{ isucon.username }}"
      ignore_errors: yes
      args:
        chdir: /tmp/benchmarker

    - name: mv the build file to /home/isucon/
      command: mv /tmp/benchmarker/benchmarker /home/isucon/
      become_user: "{{ isucon.username }}"
